{{- if or .Values.postgresqlExternalName .Values.postgresqlExternalIPs -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xnat.fullname" . }}-postgresql
  labels:
    {{- include "xnat.labels" . | nindent 4 }}
spec:
{{- if .Values.postgresqlExternalName }}
  type: ExternalName
  externalName: {{ .Values.postgresqlExternalName }}
{{- else }}
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "xnat.fullname" . }}-postgresql
  labels:
    {{- include "xnat.labels" . | nindent 4 }}
subsets:
  - addresses:
      {{- range .Values.postgresqlExternalIPs }}
      - ip: {{ . | quote }}
      {{- end }}
    ports:
      - port: 5432
{{- end }}
{{- end }}
