apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ctp.fullname" . }}
  labels:
    {{- include "ctp.labels" . | nindent 4 }}
data:
  timezone: {{ .Values.timezone }}
  Launcher.properties: {{ toYaml .Values.launcherProperties | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ctp.fullname" . }}-scripts
  labels:
    {{- include "ctp.labels" . | nindent 4 }}
data:
  {{- range $path, $_:= .Files.Glob "scripts/*.script" }}
  {{ base $path }}: |-
    {{- $.Files.Get $path | nindent 4 -}}
  {{- end }}


