apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ctp.fullname" . }}
  labels:
    {{- include "ctp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ctp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ctp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ctp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.timezone }}
          ports:
            - name: http
              containerPort: 1080
              protocol: TCP
          volumeMounts:
            - name: config-java
              mountPath: /JavaPrograms/CTP/Launcher.properties
              subPath: Launcher.properties
              readOnly: true
            - name: scripts
              mountPath: /JavaPrograms/CTP/scripts
            - name: config-xml
              mountPath: /JavaPrograms/CTP/config.xml
              subPath: config.xml
              readOnly: true
            - name: config-xml
              mountPath: /JavaPrograms/CTP/users.xml
              subPath: users.xml
              readOnly: true
            - name: logs
              mountPath: /JavaPrograms/CTP/logs 
            {{- range $volume, $v := .Values.volumes }}
            - mountPath: {{ $v.mountPath | quote }}
              name: {{ $volume | quote }}
            {{- end }}
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-logstream
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: alpine
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["/bin/sh", "-c", "tail -f /JavaPrograms/CTP/logs/ctp.log"]
          volumeMounts:
            - name: logs
              mountPath: /JavaPrograms/CTP/logs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-java
          configMap:
            name: {{ include "ctp.fullname" . }}
        - name: config-xml
          secret:
            secretName: {{ include "ctp.fullname" . }}
        - name: scripts
          configMap:
            name: {{ include "ctp.fullname" . }}-scripts
        - name: logs
          emptyDir: {}    
        {{- $context := . -}}
        {{- range $volume, $v := .Values.volumes }}
        - name: {{ $volume }}
          persistentVolumeClaim:
            claimName: {{ if $v.existingClaim }}{{ $v.existingClaim | quote }}{{ else }}{{ $volume }}-{{ include "ctp.fullname" $context }}{{ end }}
        {{- end }}
