apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctp.fullname" . }}
  labels:
    {{- include "ctp.labels" . | nindent 4 }}
type: Opaque
stringData:
  users.xml: |
    <users mode="digest">
    {{- range $username, $u := .Values.users }}
      <user
        password={{ $u.password | default (randAlphaNum 22) | quote }}
        username={{ $username | quote }}>
        {{- range $u.roles }}
          <role>{{ . }}</role>
        {{- end }}
      </user>
    {{- end }}
    </users>
