# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  config.vm.box = "ubuntu/focal64"
  #config.vm.hostname = "ais-dev"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SCRIPT
    FACTS_D='/etc/ansible/facts.d'
    REQUIREMENTS_YML='/vagrant/ansible/requirements.yml'
    apt-get update
    apt-get -y install \
      python3 \
      python3-pip
    python3 -m pip install ansible
    set -x
    if [ -f $REQUIREMENTS_YML ]; then
      su - vagrant -c "ansible-galaxy collection install -r $REQUIREMENTS_YML"
      su - vagrant -c "ansible-galaxy role install -r $REQUIREMENTS_YML"
    fi
    if ! [ -f ${FACTS_D}/vagrant.fact ]; then
      mkdir -p "${FACTS_D}"
      cat <<EOT >${FACTS_D}/vagrant.fact
[default]
user=vagrant
EOT
    fi
  SCRIPT

  config.vm.provision :ansible_local do |ansible|
    ansible.extra_vars = {"group_members": ["vagrant"]}
    ansible.groups = {
      "docker_swarm_manager" => ["swarm"],
      "microk8s" => ["k8s"]
    }
    ansible.playbook = "ansible/development.yaml"
  end

  config.vm.define "k8s", primary: true do |n|
    n.vm.hostname = "k8s"
  end

  config.vm.define "swarm", autostart: false do |n|
    n.vm.hostname = "swarm"
  end
end
