apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monai-label.fullname" . }}
  labels:
    {{- include "monai-label.labels" . | nindent 4 }}
data:
  .env: |-
    {{- tpl ($.Files.Get "conf/env.tmpl") . | nindent 4 }}
  logging_config.json: |-
    {{- tpl ($.Files.Get "conf/logging_config.json") . | nindent 4 }}
{{- if .Values.extraCerts }}
  ca-certificates.crt: |
    {{- .Values.extraCerts | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monai-label.fullname" . }}-ohifv3
  labels:
    {{- include "monai-label.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    {{- tpl ($.Files.Get "plugins/ohifv3/config/nginx.conf") . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monai-label.fullname" . }}-entrypoint
  labels:
    {{- include "monai-label.labels" . | nindent 4 }}
data:
  monailabel.sh: |-
    {{- tpl ($.Files.Get "conf/entrypoint.sh") . | nindent 4 }}
