apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monai-label.fullname" . }}
  labels:
    {{- include "monai-label.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "monai-label.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "monai-label.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "monai-label.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          # https://www.uvicorn.org/#command-line-options
          args:
          - bash
          - -c
          - |
            cd $HOME
            set -x
            [[ -d ./apps/{{ .Values.apps }} ]] \
             || monailabel apps --download --name {{ .Values.apps }} --output apps
            [[ -d ./datasets/{{ .Values.datasets }} ]] \
             || monailabel datasets --download --name {{ .Values.datasets }} --output datasets
            monailabel start_server --app apps/{{ .Values.apps }} --studies {{ .Values.studies }} --host 0.0.0.0 --port 8000 --conf {{ .Values.conf }} --dryrun
            source .env
            #exec tail -f /dev/null
            exec uvicorn monailabel.app:app --host=0.0.0.0 --port=8000 --log-level=info --no-access-log --workers=4 --forwarded-allow-ips='*' --proxy-headers
            #exec uvicorn monailabel.app:app --host='0.0.0.0' --port=8000 --log-level=info \
            #--no-access-log \
            #--workers=4 \
            #{{ .Values.ingress.enabled | ternary "--forwarded-allow-ips='*'" "--forwarded-allow-ips='127.0.0.1'" }} \
            #{{ .Values.ingress.enabled | ternary "--proxy-headers" "--no-proxy-headers" }}
          env:
          - {name: HOME, value: /home/user}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "monai-label.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: shm-device
              mountPath: /dev/shm
            - name: user-home
              mountPath: /home/user
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: shm-device
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.shmSize }}
        - name: user-home
          emptyDir: {}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
