apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "monai-label.fullname" . }}
  labels:
    {{- include "monai-label.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-hostpath
