---
name: Bug report
description: Create a report to help us improve
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the problem.
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: input
    validations:
      required: true
    attributes:
      label: XNAT Chart Version
      description: Release of XNAT chart you are running.
      placeholder: e.g. 0.6.3
  - type: input
    attributes:
      label: Version of Helm
      description: Run `helm version`.
  - type: input
    attributes:
      label: Version of Kubernetes
      description: Run `kubectl version`.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here. This can be logs, environment specific caveats, plugins, etc.
