{{- $context := . -}}
{{- range $name, $c := .Values.volumes }}
{{- if .existingClaim }}
{{- else }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "xnat-web.fullname" $context }}-{{ $name }}
  labels:
    {{- include "xnat-web.labels" $context | nindent 4 }}
spec:
  accessModes: [ {{ $c.accessMode | quote }} ]
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ $c.size | quote }}
  {{- if $c.storageClass }}
  storageClassName: {{ $c.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
