{{- $context := . -}}
{{- range $volumeName, $volume := .Values.volumes }}
{{- if .existingClaim }}
{{- else if .size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "xnat-web.fullname" $context }}-{{ $volumeName }}
  labels:
    {{- include "xnat-web.labels" $context | nindent 4 }}
spec:
  accessModes: [ {{ .accessMode | quote }} ]
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ $volume.size | quote }}
  {{- if or $volume.storageClass $.Values.global.storageClass }}
  storageClassName: {{ $volume.storageClass|default $.Values.global.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
