{{- $context := . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "xnat-web.fullname" $context }}-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "xnat-web.fullname" $context }}-bind
subjects:
- kind: ServiceAccount
  name: {{ include "xnat-web.serviceAccountName" $context }}
roleRef:
  kind: Role
  name: {{ include "xnat-web.fullname" $context }}-role
  apiGroup: rbac.authorization.k8s.io
---
