apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xnat-web.fullname" . }}
  labels:
    {{- include "xnat-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  xnat-conf.properties: |
    #
    # xnat-conf.properties
    # XNAT http://www.xnat.org
    # Copyright (c) 2016, Washington University School of Medicine
    # All Rights Reserved
    #
    # Released under the Simplified BSD.
    #
    datasource.driver=org.postgresql.Driver
    datasource.url=jdbc:postgresql://{{ template "xnat-web.postgresql.fullname" . }}{{ if not (has (toString .Values.global.postgresql.postgresqlExternalPort) (list "<nil>" "" "5432")) }}{{ print ":" .Values.global.postgresql.postgresqlExternalPort }}{{ end }}/{{ template "xnat-web.postgresql.postgresqlDatabase" . }}
    datasource.username={{ template "xnat-web.postgresql.postgresqlUsername" . }}
    datasource.password={{ template "xnat-web.postgresql.postgresqlPassword" . }}
    hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.hbm2ddl.auto=update
    hibernate.show_sql=false
    hibernate.cache.use_second_level_cache=true
    hibernate.cache.use_query_cache=true

{{- range $plugin, $p := .Values.plugins }}
{{- if $p }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xnat-web.fullname" $ }}-plugin-{{ $plugin }}
  labels:
    {{- include "xnat-web.labels" $ | nindent 4 }}
type: Opaque
stringData:
{{- range $p }}
  {{ .provider.id }}-provider.properties: |
  {{- include "xnat-web.envify" (list "" .) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}

