{{- range $plugin, $p := .Values.plugins }}
{{- if $p }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xnat-web.fullname" $ }}-plugin-{{ $plugin }}
  labels:
    {{- include "xnat-web.labels" $ | nindent 4 }}
type: Opaque
stringData:
{{- range $p }}
  {{ .provider.id }}-provider.properties: |
  {{- include "xnat-web.envify" (list "" .) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}

