apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ include "apache-artemis.fullname" . }}
  labels:
    {{- include "apache-artemis.labels" . | nindent 4 }}
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "apache-artemis.fullname" .)) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
  # set to existing secret data or generate a random one when not exists
{{- $BROKERURL := (get $secretData "brokerUrl") | default ((include "apache-artemis.brokerUrl" .) | b64enc) }}
{{- $USERNAME := (get $secretData "username") | default (.Values.auth.username | b64enc) }}
{{- $PASSWORD := (get $secretData "password") | default (randAlphaNum 32 | b64enc) }}
  brokerUrl: {{ $BROKERURL | quote }} 
  username: {{ $USERNAME | quote }}
  password: {{ $PASSWORD | quote }}
