title: Australian Imaging Service - Helm Charts
email: 
description: >- # this means to ignore newlines until "baseurl:"
  A national initiative for secure imaging management and analysis
baseurl: "/charts" # the subpath of your site, e.g. /blog
url: "https://australian-imaging-service.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: australian-imaging-service

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman 
plugins:
  - jekyll-feed
