{{- with (index .Values "xnat-web") -}}
{{- if .gateway.enabled -}}
{{- $svcPort := .service.port -}}
{{- $gatewayName := .gateway.gatewayName | default (include "xnat-web.fullname" $) -}}
{{- $gatewayNamespace := .gateway.gatewayNamespace | default $.Release.Namespace -}}
---
{{- if .gateway.http }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  {{- if and (.gateway.https) (.gateway.redirectHttpToHttps) }}
  name: {{ include "xnat-web.fullname" $ }}-https-redirect
  {{- else }}
  name: {{ include "xnat-web.fullname" $ }}-http
  {{- end }}
  labels:
    {{- include "xnat-web.labels" $ | nindent 4 }}
spec:
  parentRefs:
  {{ range $index, $elem := .gateway.http.hosts }}
  - kind: Gateway
    name: {{ $gatewayName }}
    sectionName: {{ $elem.listenerName | default (print "http-" $index) }}
    namespace: {{ $gatewayNamespace }}
  {{- end }}
  hostnames:
  {{- range .gateway.http.hosts }}
  - {{ .host | quote }}
  {{- end }}
  rules:
  {{- if and (.gateway.https) (.gateway.redirectHttpToHttps) }}
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: 443
  {{- end }}
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "xnat-web.fullname" $ }}-headless
      port: {{ $svcPort }}
    {{- if or (.gateway.httpRoutesRequestTimeout) (.gateway.httpRoutesBackendRequestTimeout) }}
    timeouts:
      {{- if .gateway.httpRoutesRequestTimeout }}
      request: {{ .gateway.httpRoutesRequestTimeout }}
      {{- end }}
      {{- if .gateway.httpRoutesBackendRequestTimeout }}
      backendRequest: {{ .gateway.httpRoutesBackendRequestTimeout }}
      {{- end }}
    {{- end }}
{{- end }}
---
{{- if .gateway.https }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "xnat-web.fullname" $ }}-https
  labels:
    {{- include "xnat-web.labels" $ | nindent 4 }}
spec:
  parentRefs:
  {{ range $index, $elem := .gateway.https.hosts }}
  - kind: Gateway
    name: {{ $gatewayName }}
    sectionName: {{ $elem.listenerName | default (print "https-" $index) }}
    namespace: {{ $gatewayNamespace }}
  {{- end }}
  hostnames:
  {{- range .gateway.https.hosts }}
  - {{ .host | quote }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "xnat-web.fullname" $ }}-headless
      port: {{ $svcPort }}
    {{- if or (.gateway.httpRoutesRequestTimeout) (.gateway.httpRoutesBackendRequestTimeout) }}
    timeouts:
      {{- if .gateway.httpRoutesRequestTimeout }}
      request: {{ .gateway.httpRoutesRequestTimeout }}
      {{- end }}
      {{- if .gateway.httpRoutesBackendRequestTimeout }}
      backendRequest: {{ .gateway.httpRoutesBackendRequestTimeout }}
      {{- end }}
    {{- end }}
{{- end }}
---
{{- if .gateway.createNoHostnameListenerAndRoute }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "xnat-web.fullname" $ }}-http-nohostname
  labels:
    {{- include "xnat-web.labels" $ | nindent 4 }}
spec:
  parentRefs:
  - kind: Gateway
    name: {{ $gatewayName }}
    sectionName: http-nohostname
    namespace: {{ $gatewayNamespace }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "xnat-web.fullname" $ }}-headless
      port: {{ $svcPort }}
    {{- if or (.gateway.httpRoutesRequestTimeout) (.gateway.httpRoutesBackendRequestTimeout) }}
    timeouts:
      {{- if .gateway.httpRoutesRequestTimeout }}
      request: {{ .gateway.httpRoutesRequestTimeout }}
      {{- end }}
      {{- if .gateway.httpRoutesBackendRequestTimeout }}
      backendRequest: {{ .gateway.httpRoutesBackendRequestTimeout }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}