{{- with (index .Values "xnat-web") -}}
{{- range $name, $c := .volumes }}
{{- if .existingClaim }}
{{- else if .size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "xnat-web.fullname" $ }}-{{ $name }}
  labels:
    {{- include "xnat-web.labels" $ | nindent 4 }}
spec:
  accessModes: [ {{ $c.accessMode | quote }} ]
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ $c.size | quote }}
  {{- if $c.storageClass }}
  storageClassName: {{ $c.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
