{{- with (index .Values "xnat-web") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xnat-web.fullname" $ }}-admin
  labels:
    {{- include "xnat-web.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: kubernetes.io/basic-auth
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" $.Release.Namespace (printf "%s-admin" (include "xnat-web.fullname" $))) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set to existing secret data or generate a random one when not exists
  {{- $LOGIN := (get $secretData "login") | default ("admin" | b64enc) }}
  {{- $PASSWORD := (get $secretData "password") | default (randAlphaNum 32 | b64enc) }}
  {{- $HTPASSWD := (get $secretData "htpasswd") | default (htpasswd ($LOGIN | b64dec) ($PASSWORD | b64dec) | b64enc) }}
  {{- $PWD_HASH := (splitn ":" 2 ($HTPASSWD | b64dec))._1 | b64enc }}
  username: {{ $LOGIN | quote }}
  password: {{ $PASSWORD | quote }}
  htpasswd: {{ $HTPASSWD | quote }}
  password_hash: {{ $PWD_HASH | quote }}
{{- end }}
