#cloud-config
locale: en_AU.utf8
packages:
  - ansible
  - curl
packages_update: true
runcmd:
  - ['curl','-sS','-o/tmp/ais-playbook-charts-development.yaml','https://raw.githubusercontent.com/Australian-Imaging-Service/charts/main/contrib/ansible/development.yaml']
  - ['ansible-playbook','/tmp/ais-playbook-charts-development.yaml']
timezone: "Australia/Perth"
